---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - name: llama
        image: alpine/llama3.2:latest
        ports:
        - containerPort: 11434
---
apiVersion: v1
kind: Service
metadata:
  name: llama-service
spec:
  type: LoadBalancer
  selector:
    app: llama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llama-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: llama-service
            port: 
              number: 80
---
